import { CheckCircle2, FileSearch, ShieldAlert, XCircle } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useAppContext } from "../app-context";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader } from "../components/ui/card";
import { ApiError } from "../lib/api";
import { approveActionProposal, copilotCapabilities, getCopilotRun, isTeacherAdvisoryOnly, listActionProposals, queryCopilot, rejectActionProposal, type ActionProposal, type CopilotIntent, type CopilotRun } from "../m23/copilot";

function errorMessage(error: unknown) { return error instanceof ApiError || error instanceof Error ? error.message : "No fue posible completar la operación."; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("es-EC", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function statusTone(status: string): "neutral" | "success" | "warning" | "danger" { return status === "EXECUTED" || status === "APPROVED" ? "success" : status === "FAILED" ? "danger" : status === "REJECTED" ? "neutral" : "warning"; }

function RunDetail({ run }: { run: CopilotRun }) {
  return <Card data-testid="m23-run-detail"><CardHeader><h2 className="font-bold text-slate-900">Respuesta gobernada</h2><p className="mt-1 text-sm text-slate-500">La respuesta es asesora: la evidencia y el juicio humano siguen siendo necesarios.</p></CardHeader><CardContent className="space-y-5">
    <div className="flex flex-wrap gap-2"><Badge tone={statusTone(run.status)}>{run.status}</Badge>{run.evidence_assessment ? <Badge tone={run.evidence_assessment === "SUFFICIENT" ? "success" : "warning"}>Evidencia {run.evidence_assessment}</Badge> : null}</div>
    {run.answer ? <div><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">Respuesta</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{run.answer}</p></div> : <p className="text-sm text-slate-500">La ejecución aún no produjo una respuesta.</p>}
    {run.failure_code ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">Código de control: {run.failure_code}</div> : null}
    <div><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">Citas autorizadas</h3><ul className="mt-2 space-y-2">{run.citations.length ? run.citations.map(c => <li key={c} className="break-all rounded-lg bg-slate-50 p-2 font-mono text-xs text-slate-600">{c}</li>) : <li className="text-sm text-slate-500">Sin citas visibles.</li>}</ul></div>
    <div><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">Limitaciones</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{run.limitations.length ? run.limitations.map(item => <li key={item}>{item}</li>) : <li>Sin limitaciones adicionales reportadas.</li>}</ul></div>
    <div className="rounded-xl bg-slate-50 p-4"><h3 className="text-xs font-bold uppercase tracking-wide text-slate-400">Proveniencia</h3><dl className="mt-2 grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><div><dt>Política</dt><dd className="font-semibold">{run.provenance.policy_key ?? "—"} {run.provenance.policy_version ?? ""}</dd></div><div><dt>Plantilla</dt><dd className="font-semibold">{run.provenance.prompt_key ?? "—"} {run.provenance.prompt_version ?? ""}</dd></div><div><dt>Modelo gobernado</dt><dd className="font-semibold">{run.provenance.provider_key ?? "—"} / {run.provenance.model_key ?? "—"}</dd></div><div><dt>Completado</dt><dd className="font-semibold">{formatDate(run.completed_at)}</dd></div></dl></div>
  </CardContent></Card>;
}

function ProposalDetail({ proposal, canApprove }: { proposal: ActionProposal; canApprove: boolean }) {
  const queryClient = useQueryClient(); const [note, setNote] = useState(""); const [reason, setReason] = useState("");
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["m23-action-proposals"] });
  const approve = useMutation({ mutationFn: () => approveActionProposal(proposal.id, note), onSuccess: refresh });
  const reject = useMutation({ mutationFn: () => rejectActionProposal(proposal.id, reason), onSuccess: refresh });
  return <Card><CardHeader><h2 className="font-bold text-slate-900">Propuesta de acción</h2></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Badge tone={statusTone(proposal.status)}>{proposal.status}</Badge><Badge tone="neutral">{proposal.action_type}</Badge></div><p className="text-sm leading-6 text-slate-700">{proposal.rationale}</p><div className="rounded-xl bg-slate-50 p-3 text-xs"><div className="font-bold uppercase text-slate-400">Estudiante objetivo</div><div className="mt-1 break-all font-mono text-slate-700">{proposal.target_student_profile_id}</div></div><div><div className="text-xs font-bold uppercase text-slate-400">Citas de evidencia</div>{proposal.evidence_citations.map(c => <div key={c} className="mt-2 break-all font-mono text-xs text-slate-600">{c}</div>)}</div>{proposal.decision_note ? <div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-700">Decisión registrada: {proposal.decision_note}</div> : null}
    {canApprove && proposal.status === "PROPOSED" ? <div className="space-y-3 border-t border-slate-100 pt-4"><label className="block text-sm font-semibold text-slate-700">Nota de aprobación (opcional)<textarea value={note} maxLength={2000} onChange={e => setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-2 text-sm font-normal" /></label><label className="block text-sm font-semibold text-slate-700">Motivo de rechazo<textarea value={reason} maxLength={2000} onChange={e => setReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-2 text-sm font-normal" /></label>{approve.isError || reject.isError ? <div className="text-sm text-rose-700">{errorMessage(approve.error ?? reject.error)}</div> : null}<div className="grid gap-2 sm:grid-cols-2"><Button disabled={approve.isPending || reject.isPending} onClick={() => approve.mutate()}><CheckCircle2 className="mr-2 h-4 w-4" />Aprobar y ejecutar</Button><Button variant="danger" disabled={!reason.trim() || approve.isPending || reject.isPending} onClick={() => reject.mutate()}><XCircle className="mr-2 h-4 w-4" />Rechazar</Button></div></div> : <p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{canApprove ? "Esta propuesta ya tiene una decisión." : "Tu contexto puede consultar propuestas visibles, pero no decidirlas."}</p>}</CardContent></Card>;
}

export function CopilotWorkspacePage() {
  const { bootstrap } = useAppContext(); const capabilities = copilotCapabilities(bootstrap.permissions); const teacherOnly = isTeacherAdvisoryOnly(bootstrap.permissions);
  const [intent, setIntent] = useState<CopilotIntent>(teacherOnly ? "STUDENT_SUPPORT_SUMMARY" : "INSTITUTION_RISK_SUMMARY"); const [requestText, setRequestText] = useState(""); const [studentId, setStudentId] = useState(""); const [runId, setRunId] = useState<string | null>(null); const [selectedProposalId, setSelectedProposalId] = useState<string | null>(null);
  const query = useMutation({ mutationFn: () => queryCopilot({ intent, request_text: requestText.trim(), ...(intent === "STUDENT_SUPPORT_SUMMARY" ? { target_student_profile_id: studentId.trim() } : {}) }), onSuccess: response => setRunId(response.run_id) });
  const run = useQuery({ queryKey: ["m23-run", runId], queryFn: () => getCopilotRun(runId!), enabled: Boolean(runId), retry: false });
  const proposals = useQuery({ queryKey: ["m23-action-proposals"], queryFn: listActionProposals, enabled: capabilities.canUse && !teacherOnly, retry: false }); const selected = proposals.data?.find(p => p.id === selectedProposalId) ?? proposals.data?.[0];
  if (!capabilities.canUse) return <Card><CardContent className="flex min-h-72 flex-col items-center justify-center p-6 text-center"><ShieldAlert className="h-11 w-11 text-rose-500" /><h1 className="mt-4 text-xl font-bold">Copiloto no disponible</h1><p className="mt-2 text-sm text-slate-500">Tu contexto autenticado no posee copilot.use.</p></CardContent></Card>;
  const invalid = !requestText.trim() || (intent === "STUDENT_SUPPORT_SUMMARY" && !studentId.trim());
  return <div className="space-y-5" data-testid="m23-copilot-workspace"><div><div className="flex gap-2"><Badge tone="success">M23 · Copiloto gobernado</Badge>{teacherOnly ? <Badge tone="neutral">Asesoría por estudiante</Badge> : <Badge tone="neutral">Evidencia y revisión humana</Badge>}</div><h1 className="mt-3 text-3xl font-bold">Copiloto gobernado</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Las respuestas no son verdad operativa ni ejecutan cambios. Toda acción requiere la decisión humana autorizada.</p></div>
    <Card><CardHeader><h2 className="font-bold">Consulta</h2></CardHeader><CardContent><div className="grid gap-3"><label className="text-sm font-semibold">Tipo de consulta<select value={intent} onChange={e => setIntent(e.target.value as CopilotIntent)} disabled={teacherOnly} className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="INSTITUTION_RISK_SUMMARY">Resumen institucional de riesgo</option><option value="STUDENT_SUPPORT_SUMMARY">Resumen de apoyo al estudiante</option></select></label>{intent === "STUDENT_SUPPORT_SUMMARY" ? <label className="text-sm font-semibold">ID de estudiante objetivo<input value={studentId} onChange={e => setStudentId(e.target.value)} placeholder="UUID del perfil estudiantil autorizado" className="mt-1 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label> : null}<label className="text-sm font-semibold">Pregunta<textarea value={requestText} maxLength={6000} onChange={e => setRequestText(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm font-normal" /></label><Button disabled={invalid || query.isPending} onClick={() => query.mutate()} data-testid="m23-submit-query"><FileSearch className="mr-2 h-4 w-4" />{query.isPending ? "Consultando…" : "Generar asesoría"}</Button>{query.isError ? <div className="text-sm text-rose-700">{errorMessage(query.error)}</div> : null}</div></CardContent></Card>
    {run.isPending ? <Card><CardContent className="p-5 text-sm text-slate-500">Cargando resultado gobernado…</CardContent></Card> : null}{run.data ? <RunDetail run={run.data} /> : null}{run.isError ? <Card><CardContent className="p-5 text-sm text-rose-700">{errorMessage(run.error)}</CardContent></Card> : null}
    {!teacherOnly ? <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><h2 className="font-bold">Propuestas visibles</h2><p className="mt-1 text-sm text-slate-500">Solo son propuestas; no existe creación manual de acciones.</p></CardHeader><CardContent>{proposals.isPending ? <div className="text-sm text-slate-500">Cargando propuestas…</div> : proposals.isError ? <div className="text-sm text-rose-700">{errorMessage(proposals.error)}</div> : <div className="space-y-2">{proposals.data?.length ? proposals.data.map(p => <button key={p.id} type="button" onClick={() => setSelectedProposalId(p.id)} className="w-full rounded-xl border border-slate-200 p-3 text-left hover:bg-slate-50"><Badge tone={statusTone(p.status)}>{p.status}</Badge><div className="mt-2 text-sm font-semibold">{p.action_type}</div><div className="mt-1 truncate text-xs text-slate-500">{p.target_student_profile_id}</div></button>) : <div className="text-sm text-slate-500">Sin propuestas visibles.</div>}</div>}</CardContent></Card>{selected ? <ProposalDetail proposal={selected} canApprove={capabilities.canApprove} /> : null}</div> : null}
  </div>;
}
