import { ExternalLink,ShieldAlert } from "lucide-react";
import { useAppContext } from "../app-context";
import { findModule,moduleCapabilityState,modulesForContext } from "../navigation";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card,CardContent,CardHeader } from "../components/ui/card";
import { TeacherPwaPage } from "./teacher-pwa-page";

export function WorkspacePage({moduleId}:{moduleId:string}){const{bootstrap}=useAppContext();const module=findModule(moduleId);const allowedIds=new Set(modulesForContext(bootstrap).map(x=>x.id));if(!module||!allowedIds.has(module.id)){return<Card><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><ShieldAlert className="h-10 w-10 text-rose-500"/><h1 className="mt-4 text-xl font-bold">Espacio no disponible</h1><p className="mt-2 max-w-lg text-sm text-slate-500">El frontend no mostrará un módulo si tu contexto autenticado no tiene su permiso de acceso.</p></CardContent></Card>;}if(module.id==="teacher")return<TeacherPwaPage/>;const capability=moduleCapabilityState(module,bootstrap);const legacyPath=module.legacyPath;return<div className="space-y-5" data-testid={`workspace-${module.id}`}><div><div className="flex gap-2"><Badge tone="neutral">{module.audience}</Badge>{capability==="disabled"?<Badge tone="warning">Capability deshabilitada</Badge>:null}</div><h1 className="mt-3 text-3xl font-bold">{module.label}</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">{module.description}</p></div><Card><CardHeader><h2 className="font-bold">Vista unificada de {module.label}</h2><p className="mt-1 text-sm text-slate-500">M15 establece el shell y contexto de permisos; las reglas backend congeladas se preservan.</p></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase text-slate-400">Permiso</div><div className="mt-2 font-mono text-sm">{module.permission}</div></div><div className="rounded-xl bg-slate-50 p-4"><div className="text-xs font-bold uppercase text-slate-400">Transición</div><div className="mt-2 text-sm font-semibold">Shell React activo · consola heredada preservada</div></div></div><Button onClick={()=>window.location.assign(legacyPath)} className="mt-5 gap-2" data-testid={`legacy-${module.id}`}>Abrir consola operativa actual<ExternalLink className="h-4 w-4"/></Button></CardContent></Card></div>}
