import type { TeacherOfflineAttendanceBase, TeacherOfflineQueuedOperation, TeacherOfflineSnapshot } from "../types/teacher-offline";
const DB_NAME="education-os-teacher-offline", DB_VERSION=1, SNAPSHOTS="snapshots", OPERATIONS="operations", PARTITION_INDEX="partitionKey";
interface SnapshotRecord { partitionKey:string; savedAt:string; snapshot:TeacherOfflineSnapshot; }
function result<T>(r:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function done(tx:IDBTransaction):Promise<void>{return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(SNAPSHOTS))db.createObjectStore(SNAPSHOTS,{keyPath:"partitionKey"});if(!db.objectStoreNames.contains(OPERATIONS)){const s=db.createObjectStore(OPERATIONS,{keyPath:"queueKey"});s.createIndex(PARTITION_INDEX,"partitionKey",{unique:false});}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function saveTeacherOfflineSnapshot(partitionKey:string,snapshot:TeacherOfflineSnapshot){const db=await openDb();try{const tx=db.transaction(SNAPSHOTS,"readwrite");tx.objectStore(SNAPSHOTS).put({partitionKey,savedAt:new Date().toISOString(),snapshot} satisfies SnapshotRecord);await done(tx);}finally{db.close();}}
export async function loadTeacherOfflineSnapshot(partitionKey:string):Promise<TeacherOfflineSnapshot|null>{const db=await openDb();try{const tx=db.transaction(SNAPSHOTS,"readonly");const record=await result(tx.objectStore(SNAPSHOTS).get(partitionKey)) as SnapshotRecord|undefined;await done(tx);return record?.snapshot??null;}finally{db.close();}}
export async function deleteTeacherOfflineSnapshot(partitionKey:string){const db=await openDb();try{const tx=db.transaction(SNAPSHOTS,"readwrite");tx.objectStore(SNAPSHOTS).delete(partitionKey);await done(tx);}finally{db.close();}}
export async function putTeacherOfflineOperation(operation:TeacherOfflineQueuedOperation){const db=await openDb();try{const tx=db.transaction(OPERATIONS,"readwrite");tx.objectStore(OPERATIONS).put(operation);await done(tx);}finally{db.close();}}
export async function listTeacherOfflineOperations(partitionKey:string):Promise<TeacherOfflineQueuedOperation[]>{const db=await openDb();try{const tx=db.transaction(OPERATIONS,"readonly");const rows=await result(tx.objectStore(OPERATIONS).index(PARTITION_INDEX).getAll(partitionKey)) as TeacherOfflineQueuedOperation[];await done(tx);return rows.sort((a,b)=>a.createdAt.localeCompare(b.createdAt));}finally{db.close();}}
export async function deleteTeacherOfflineOperation(queueKey:string){const db=await openDb();try{const tx=db.transaction(OPERATIONS,"readwrite");tx.objectStore(OPERATIONS).delete(queueKey);await done(tx);}finally{db.close();}}
export async function purgeTeacherOfflinePartition(partitionKey:string){const db=await openDb();try{const tx=db.transaction([SNAPSHOTS,OPERATIONS],"readwrite");tx.objectStore(SNAPSHOTS).delete(partitionKey);const store=tx.objectStore(OPERATIONS),index=store.index(PARTITION_INDEX),cursor=index.openKeyCursor(IDBKeyRange.only(partitionKey));cursor.onsuccess=()=>{const c=cursor.result;if(!c)return;store.delete(c.primaryKey);c.continue();};await done(tx);}finally{db.close();}}
export function applyAttendanceStateToSnapshot(snapshot:TeacherOfflineSnapshot,classSessionId:string,assignmentId:string,state:TeacherOfflineAttendanceBase):TeacherOfflineSnapshot{const code=snapshot.attendance_codes.find(x=>x.id===state.attendance_code_id);return {...snapshot,classes:snapshot.classes.map(c=>({...c,sessions:c.sessions.map(s=>s.session.id!==classSessionId?s:{...s,attendance:s.attendance.map(r=>r.student_section_assignment_id!==assignmentId?r:{...r,attendance_record_id:state.attendance_record_id,attendance_code_id:state.attendance_code_id,attendance_code:code?.code??null,attendance_label:code?.label??null,minutes_late:state.minutes_late,note:state.note})})}))};}
